/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/hot-air-ballon/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pSphere16_1.geometry} material={materials.blinn6SG} />
      <mesh geometry={nodes.pSphere16_1_1.geometry} material={materials.blinn7SG} />
      <mesh geometry={nodes.pSphere16_1_2.geometry} material={materials.blinn10SG} />
    </group>
  )
}

useGLTF.preload('/model.glb')
